// import DataProp from "../types/dataType";

// const dataWords: DataProp = {
//   fourLetterWords: [
//     "lamp",
//     "tree",
//     "ball",
//     "book",
//     "time",
//     "desk",
//     "love",
//     "life",
//     "star",
//     "note",
//     "blue",
//     "fish",
//     "sand",
//     "cold",
//     "warm",
//     "king",
//     "queen",
//     "moon",
//     "wind",
//     "rain",
//     "fire",
//     "game",
//     "clay",
//     "wish",
//     "cake",
//     "coat",
//     "song",
//     "tide",
//     "lake",
//     "soil",
//     "park",
//     "milk",
//     "jump",
//     "kite",
//     "palm",
//     "leaf",
//     "dawn",
//     "maze",
//     "hope",
//     "gear",
//     "seat",
//     "fast",
//     "snow",
//     "wake",
//     "salt",
//     "duck",
//     "fish",
//     "card",
//     "bake",
//     "roll",
//     "path",
//     "code",
//     "rock",
//     "flip",
//     "dust",
//     "plow",
//     "skip",
//     "firm",
//     "char",
//     "stamp",
//     "bike",
//     "neat",
//     "luck",
//     "shade",
//     "tray",
//     "loud",
//     "crop",
//     "risk",
//     "pond",
//     "surf",
//     "rest",
//     "tuck",
//     "grab",
//     "tune",
//     "glow",
//     "pave",
//     "ship",
//     "moth",
//     "flap",
//     "wade",
//     "drip",
//     "pill",
//     "perk",
//     "snap",
//     "dash",
//     "plum",
//     "clip",
//     "whip",
//     "turn",
//     "rays",
//     "dark",
//     "pout",
//     "blow",
//     "fold",
//     "crew",
//     "grip",
//     "grip",
//     "seal",
//     "mint",
//     "hush",
//     "slam",
//     "rock",
//     "turn",
//     "slide",
//     "fold",
//     "whiz",
//     "skip",
//     "toss",
//     "bank",
//     "loop",
//     "chalk",
//     "moat",
//     "gust",
//     "snap",
//     "peel",
//     "mend",
//     "tip",
//     "clam",
//     "turf",
//     "thaw",
//     "leap",
//     "fume",
//     "perk",
//     "slip",
//     "jolt",
//     "shift",
//     "plow",
//     "trim",
//     "zone",
//     "blow",
//     "rave",
//     "volt",
//     "plow",
//     "flap",
//     "cane",
//     "dove",
//     "blip",
//     "task",
//   ],
//   fiveLetterWords: [
//     "apple",
//     "table",
//     "chair",
//     "piano",
//     "plane",
//     "music",
//     "house",
//     "beach",
//     "liver",
//     "stone",
//     "watch",
//     "plant",
//     "sweet",
//     "dance",
//     "light",
//     "dream",
//     "water",
//     "build",
//     "peach",
//     "flame",
//     "paint",
//     "smile",
//     "vocal",
//     "petty",
//     "brush",
//     "heart",
//     "track",
//     "sound",
//     "candy",
//     "cloud",
//     "pearl",
//     "grape",
//     "sweep",
//     "fight",
//     "break",
//     "clean",
//     "quiet",
//     "glove",
//     "latch",
//     "plaza",
//     "prize",
//     "tiger",
//     "chime",
//     "pluck",
//     "shine",
//     "craft",
//     "feast",
//     "group",
//     "sharp",
//     "lunch",
//     "march",
//     "chase",
//     "shout",
//     "blaze",
//     "creek",
//     "loose",
//     "juice",
//     "peace",
//     "quick",
//     "front",
//     "slice",
//     "carve",
//     "breeze",
//     "focus",
//     "bless",
//     "dream",
//     "clash",
//     "brisk",
//     "stone",
//     "swoop",
//     "press",
//     "light",
//     "globe",
//     "blunt",
//     "spike",
//     "tough",
//     "clamp",
//     "brave",
//     "drain",
//     "stick",
//     "poise",
//     "crack",
//     "spree",
//     "plaza",
//     "fresh",
//     "brace",
//     "plumb",
//     "swirl",
//     "shift",
//     "swoop",
//     "brisk",
//     "drift",
//     "blink",
//     "flick",
//     "flush",
//     "whine",
//     "frill",
//     "chime",
//     "bless",
//     "swoop",
//     "prong",
//     "creep",
//     "vocal",
//     "clamp",
//     "pouch",
//     "front",
//     "stare",
//     "glove",
//     "vivid",
//     "globe",
//     "sweet",
//     "bride",
//     "snack",
//     "spike",
//     "latch",
//     "straw",
//     "shout",
//     "creek",
//     "grip",
//     "bluff",
//     "pouch",
//     "stuck",
//     "trick",
//     "smash",
//     "grape",
//     "latch",
//     "plaza",
//     "pluck",
//     "sweep",
//     "crust",
//   ],
//   sixLetterWords: [
//     "garden",
//     "forest",
//     "bricks",
//     "dancey",
//     "bright",
//     "wonder",
//     "castle",
//     "gloves",
//     "sight",
//     "orange",
//     "hammer",
//     "circle",
//     "people",
//     "silver",
//     "mounts",
//     "clouds",
//     "coast",
//     "globe",
//     "energy",
//     "apple",
//     "bridge",
//     "shoes",
//     "voice",
//     "bloom",
//     "dreams",
//     "guitar",
//     "honey",
//     "salmon",
//     "flock",
//     "straw",
//     "skirt",
//     "spoon",
//     "flame",
//     "bison",
//     "bride",
//     "piano",
//     "tiger",
//     "stone",
//     "river",
//     "sweep",
//     "chase",
//     "cliff",
//     "adore",
//     "bacon",
//     "swoop",
//     "chill",
//     "flood",
//     "plume",
//     "merit",
//     "shove",
//     "fence",
//     "spark",
//     "spine",
//     "grape",
//     "snack",
//     "scrap",
//     "whale",
//     "scrub",
//     "plane",
//     "flock",
//     "gleam",
//     "clash",
//     "waste",
//     "whirl",
//     "jolly",
//     "chirp",
//     "trick",
//     "pride",
//     "knack",
//     "fluff",
//     "trill",
//     "spoon",
//     "twist",
//     "brisk",
//     "flick",
//     "whine",
//     "slush",
//     "stuck",
//     "shook",
//     "bliss",
//     "crisp",
//     "fluff",
//     "punch",
//     "prune",
//     "split",
//     "dreams",
//     "pouch",
//     "waste",
//     "trick",
//     "shine",
//     "swoop",
//     "brush",
//     "fluff",
//     "punch",
//     "swoop",
//     "prune",
//     "whine",
//     "pouch",
//     "split",
//     "dreams",
//     "light",
//     "glove",
//     "grape",
//     "clash",
//     "whirl",
//     "chime",
//     "trick",
//     "twist",
//     "bloom",
//     "chime",
//     "glove",
//     "smart",
//     "drain",
//     "plume",
//     "whale",
//     "breeze",
//     "waste",
//     "fluff",
//     "shout",
//     "drain",
//     "flame",
//     "shine",
//     "glove",
//     "twist",
//     "flare",
//     "blaze",
//     "chime",
//     "drink",
//     "dash",
//     "storm",
//     "chime",
//     "shout",
//     "smash",
//     "vocal",
//     "quick",
//     "brisk",
//     "blend",
//     "grip",
//     "spire",
//     "march",
//   ],
// };

// export default dataWords;

import DataProp from "../types/dataType";

const dataWords: DataProp = {
  fourLetterWords: [
    "lamp",
    "tree",
    "ball",
    "book",
    "time",
    "desk",
    "love",
    "life",
    "star",
    "note",
    "blue",
    "fish",
    "sand",
    "cold",
    "warm",
    "king",
    "moon",
    "wind",
    "rain",
    "fire",
    "game",
    "clay",
    "wish",
    "cake",
    "coat",
    "song",
    "tide",
    "lake",
    "soil",
    "park",
    "milk",
    "jump",
    "kite",
    "palm",
    "leaf",
    "dawn",
    "maze",
    "hope",
    "gear",
    "seat",
    "fast",
    "snow",
    "wake",
    "salt",
    "duck",
    "card",
    "bake",
    "roll",
    "path",
    "code",
    "rock",
    "flip",
    "dust",
    "plow",
    "skip",
    "firm",
    "char",
    "stamp",
    "bike",
    "neat",
    "luck",
    "tray",
    "loud",
    "crop",
    "risk",
    "pond",
    "surf",
    "rest",
    "tuck",
    "grab",
    "tune",
    "glow",
    "pave",
    "ship",
    "moth",
    "flap",
    "wade",
    "drip",
    "pill",
    "perk",
    "snap",
    "dash",
    "plum",
    "clip",
    "whip",
    "turn",
    "rays",
    "dark",
    "pout",
    "blow",
    "fold",
    "crew",
    "grip",
    "seal",
    "mint",
    "hush",
    "slam",
    "moat",
    "gust",
    "snap",
    "peel",
    "mend",
    "clam",
    "turf",
    "thaw",
    "leap",
    "fume",
    "slip",
    "jolt",
    "trim",
    "zone",
    "rave",
    "volt",
    "cane",
    "dove",
    "blip",
    "task",
    "vein",
    "beam",
    "fern",
    "fern",
    "herb",
    "nest",
    "vine",
    "bark",
    "twig",
  ],
  fiveLetterWords: [
    "apple",
    "table",
    "chair",
    "piano",
    "plane",
    "music",
    "house",
    "beach",
    "stone",
    "watch",
    "plant",
    "sweet",
    "dance",
    "light",
    "dream",
    "water",
    "build",
    "peach",
    "flame",
    "paint",
    "smile",
    "vocal",
    "brush",
    "heart",
    "track",
    "sound",
    "candy",
    "cloud",
    "pearl",
    "grape",
    "sweep",
    "fight",
    "break",
    "clean",
    "quiet",
    "glove",
    "latch",
    "plaza",
    "prize",
    "tiger",
    "chime",
    "pluck",
    "shine",
    "craft",
    "feast",
    "group",
    "sharp",
    "lunch",
    "march",
    "chase",
    "shout",
    "blaze",
    "creek",
    "juice",
    "peace",
    "quick",
    "front",
    "slice",
    "carve",
    "focus",
    "bless",
    "clash",
    "brisk",
    "swoop",
    "press",
    "light",
    "globe",
    "blunt",
    "spike",
    "tough",
    "clamp",
    "brave",
    "drain",
    "stick",
    "poise",
    "crack",
    "spree",
    "fresh",
    "brace",
    "plumb",
    "swirl",
    "shift",
    "swoop",
    "drift",
    "blink",
    "flick",
    "flush",
    "whine",
    "frill",
    "stare",
    "vivid",
    "bride",
    "snack",
    "spike",
    "latch",
    "straw",
    "creek",
    "grasp",
    "wrist",
    "crisp",
    "froze",
    "scout",
    "brisk",
    "pride",
    "cliff",
    "jolly",
    "whale",
    "smart",
  ],
  sixLetterWords: [
    "garden",
    "forest",
    "bricks",
    "bright",
    "wonder",
    "castle",
    "gloves",
    "orange",
    "hammer",
    "circle",
    "people",
    "silver",
    "energy",
    "bridge",
    "guitar",
    "salmon",
    "breeze",
    "dreams",
    "flicks",
    "whales",
    "planes",
    "spoons",
    "bottle",
    "strobe",
    "paddle",
    "wrench",
    "candle",
    "pebbly",
    "walnut",
    "bamboo",
    "cobalt",
    "stream",
    "plowed",
    "spring",
    "throne",
    "mantle",
    "quartz",
    "violet",
    "sprout",
    "thatch",
    "fluffy",
    "fringe",
    "swoosh",
    "knight",
    "jigsaw",
    "prance",
    "shovel",
    "shiver",
    "drinks",
    "whirls",
    "trophy",
    "trench",
    "sprint",
    "glisten",
    "snappy",
    "waddle",
    "stream",
    "whimsy",
    "prance",
    "buckle",
    "mingle",
    "tackle",
    "thrust",
    "crunch",
    "banner",
    "swoosh",
    "ripple",
    "prance",
    "blazer",
    "swoosh",
    "cuddle",
    "gritty",
  ],
};

export default dataWords;
